# Generated by Django 4.0.6 on 2022-08-04 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diarioAtividades', '0002_alter_itemtabela_atividades'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtabela',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
