# Generated by Django 4.1 on 2022-08-04 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diarioAtividades', '0003_itemtabela_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela',
            name='criada_em',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
