# Generated by Django 4.1 on 2022-08-05 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diarioAtividades', '0005_alter_atividade_duracao_alter_tabela_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtabela',
            name='tabela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itensTabela', to='diarioAtividades.tabela'),
        ),
    ]
