# Generated by Django 4.1 on 2022-08-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioAtividades', '0006_alter_itemtabela_tabela'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela',
            name='ano',
            field=models.IntegerField(default=2022),
        ),
    ]
