# Generated by Django 4.1 on 2022-08-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioAtividades', '0007_tabela_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtabela',
            name='data',
            field=models.DateField(),
        ),
    ]
