# Generated by Django 4.1 on 2022-08-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chefia',
            field=models.CharField(default='***', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='a@b.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='entrada',
            field=models.CharField(default='***', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='matricula',
            field=models.CharField(default='***', max_length=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(default='***', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='saida',
            field=models.CharField(default='***', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='saidaAlmoco',
            field=models.CharField(default='***', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='senha',
            field=models.CharField(default='***', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='setor',
            field=models.CharField(default='***', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='sobrenome',
            field=models.CharField(default='***', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='usuario',
            field=models.CharField(default='***', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='voltaAlmoco',
            field=models.CharField(default='***', max_length=100),
        ),
    ]
